azure:
  application-insights:
    instrumentation-key: fc197122-2104-4a8e-a371-ad87d71832cf
spring:
  jms:
    servicebus:
      connection-string: Endpoint=sb://experi-monitor-asb.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=F8LCf56Bd0sKLWVdKc+x5KZZXc1ziZVyi5FWZpkrWw8=
      idle-timeout: 1800000
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    sender:
      type: web