version: '2'

services:

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
      - 9411:9411

  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    mem_limit: 256M
    ports:
      - 3000:3000

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    mem_limit: 256M
    ports:
      - 9091:9090

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-config.yaml", "--log-level=DEBUG"]
    depends_on:
      - tracing-server
    volumes:
      - ./collector.yaml:/etc/otelcol-config.yaml
    ports:
      - "13133:13133" # health_check extension
      - "55680:55680" # Jaeger gRPC
      - "55679:55679" # zpages extension
      - "8889:8889"   # Prometheus exporter metrics